### ISSUE TITLE
Alert: Unexpected Fingerprint

### ISSUE THREAD

**Issue by CableMate** [nzymedefense/nzyme#1005]
Do I interpret the display wrong?
I see a contradiction. See Screenshot.

Monitored network "PYUR 16D1E" advertised with unexpected fingerprint "073a2d5abc8a02091cfccee11ab56700486da5176fe0ce1922bae75abb3cfdae".

Observed Fingerprint
    073a2d5abc8a02091cfccee11ab56700486da5176fe0ce1922bae75abb3cfdae

is the same!

**Comment by CableMate** [comment]
![UnexpectedFingerprint](https://github.com/nzymedefense/nzyme/assets/68850559/c163f138-f16e-4f59-b320-0f15edb6023f)

**Comment by lennartkoopmann** [comment]
I'm not sure I understand. It is the same fingerprint because that fingerprint is the one that was observed. Compare it to the fingerprints you configured as expected fingerprints for that BSSID and you should see that it is different, or was different when the alert was triggered.

**Comment by CableMate** [comment]
I should better formulate it so:
I would be clearer to change the alert message:  Displaing the unexpected **and** the defined fingerprint (when one is defined), would express the difference much better.
