### ISSUE TITLE
Alert: Unexpected Frequency

### ISSUE THREAD

**Issue by CableMate** [nzymedefense/nzyme#1006]
The advertised frequency is the same as the oberved
![UnexpectedFreq](https://github.com/nzymedefense/nzyme/assets/68850559/18d0a7aa-ba1a-4e95-838c-3bd52dd33c8b)

Related observation:

There is an alert: "Monitored network "PYUR 16D1E" advertised on unexpected frequency 2462MHz"
But this frequency is defined in the monitor settings:

![grafik](https://github.com/nzymedefense/nzyme/assets/68850559/f0d36377-51c2-4d8d-914f-3584cab2d45c)

**Comment by lennartkoopmann** [comment]
I believe that this is the same reason as for your other related issues: You likely changed the monitored network configuration after the alerts were triggered. You can mark the alert as resolved and it should not appear again.

I'll see if I can make the UI easier to understand for cases like this.

**Comment by CableMate** [comment]
>You likely changed the monitored network configuration after the alerts were triggered.
I assume the same. Sorry.
>I'll see if I can make the UI easier to understand for cases like this.
Currently you can say there is a information (here the frequency) displayed twice.
