### ISSUE TITLE
Alert Similar SSID

### ISSUE THREAD

**Issue by CableMate** [nzymedefense/nzyme#1007]
I set the similarty threshold to 99%. But I got a hit for 84.51%
![Similar-1](https://github.com/nzymedefense/nzyme/assets/68850559/4d588c66-eb81-44ba-b1a1-6aaaa61d3d71)
![Similar-Threshold99](https://github.com/nzymedefense/nzyme/assets/68850559/c02e8cc6-4696-4e02-a154-4a6f2aca0bd4)

**Comment by lennartkoopmann** [comment]
The alert threshold was set to 0% when the alert was triggered. You changed it to 99% after the alert was triggered.

The default 0% was a migration bug and is already fixed, shipping with the next alpha release.

**Comment by CableMate** [comment]
Thanks!
