### ISSUE TITLE
Rest Call failed (404)

### ISSUE THREAD

**Issue by CableMate** [nzymedefense/nzyme#1008]
**Describe the bug**
Sometimes  the message "REST Call failed (404)" appears

**To Reproduce**
1. Go to Wifi/Access Points
2. Click on some MAC
3. See error

**Expected behavior**
Display of the Access Point details

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.3
 - Firefox 
 - mint001 1.0
![REST call failed-1](https://github.com/nzymedefense/nzyme/assets/68850559/7b15e29e-fe28-4c0c-b96d-f19806ea58a4)
![REST call failed-2](https://github.com/nzymedefense/nzyme/assets/68850559/a2c2ea35-4350-4720-8c58-06e24d314e37)

**Comment by lennartkoopmann** [comment]
Duplicate #981
