### ISSUE TITLE
Memory consumption permanent increasing

### ISSUE THREAD

**Issue by CableMate** [nzymedefense/nzyme#1012]
Is it normal, that the memory consumption is permanent in increasing?
After a restart of nzyme-tap at (last one at 9 am) I observe:
![Memory](https://github.com/nzymedefense/nzyme/assets/68850559/6abeacc0-8263-4bd0-b07f-abef8bfe393b)
![grafik](https://github.com/nzymedefense/nzyme/assets/68850559/ebee2d04-8a74-4976-8fad-1258b2dd3d1f)
Today at 9am I added one more WLAN interface. See #1011 

Swap is switched off.
htop sorted after memory:
![grafik](https://github.com/nzymedefense/nzyme/assets/68850559/8024c657-4254-4ad4-8def-e7fd3f2fb259)

**Comment by lennartkoopmann** [comment]
You are looking at the total, system-wide memory use and not the memory use of only nzyme. Nzyme appears to be using about 750MB of heap space and is limited to 1.1GB heap space. I assume something else on your system is using all the remaining memory.
