### ISSUE TITLE
Lost TAP and UI is giving REST API FAILED and Tap Selector Stalled with spinning circle

### ISSUE THREAD

**Issue by mavacpjm** [nzymedefense/nzyme#1030]
I lost a TAP due to corrupted SSD. Now the Nzyme Server UI is giving  REST API Failed and the tap selector drop down is stuck in spinning circle and I cant select the still operational tap. Its causing the UI to push REST API failed drop down red box every time I go from one page to the next. Any idea on a quick fix to get around this, it seems if a TAP is lost, the UI shits the bed!

Appreciate the help, Im on latest alpha you just released.

**Comment by mavacpjm** [comment]
Figured out a work around its moot, force deleted the non-working TAP and UI is back operational, but I still think if it sees a TAP offline it should not cause this issue.

**Comment by lennartkoopmann** [comment]
Thank you! This should of course not happen. Do you still have your `nzyme-node` logs from when this occurred? That would tell me what went wrong.
