### ISSUE TITLE
Sensitive Network SSID Probe Detection and Notification

### ISSUE THREAD

**Issue by huwilerp** [nzymedefense/nzyme#1056]
### Feature/Change Description and Goal
The feature aims to enhance security by implementing a mechanism to alert users when their devices probe for sensitive WiFi SSIDs, ensuring they properly "Forget Wi-Network" to prevent inadvertent exposure.

### Design Considerations

Identifying sensitive WiFi SSIDs
Implementing probe detection and alerting mechanisms
User interface for alerting users

### Critical Areas for Security
Critical security areas include:

Preventing unauthorized access to sensitive network information
Protecting user privacy during alerting process
Ensuring the integrity of probe detection mechanisms
Design / Architecture
The design involves:

Maintaining a list of sensitive WiFi SSIDs
Monitoring WiFi probes for matches against the sensitive SSID list
Triggering alerts for users who fail to "Forget Wi-Network" after connecting to a sensitive SSID

### Tasks / Tickets
 Implement sensitive SSID list management
 Develop probe detection mechanism
 Implement user alerting system
 Integrate feature into existing network management system

### Threat Model

Threat Actor: A war driver intercepts WiFi probes to geolocate the exact location of the network.
Attack Vector: The attacker utilizes tools like Wigle.net or engages in wardriving to collect and analyze WiFi probes.
Impact: The attacker can pinpoint the physical location of sensitive networks, compromising their security and exposing them to potential threats.

### Mitigation:
Implement encryption mechanisms for WiFi probes to prevent interception.
Minimize the broadcasting range of WiFi signals to reduce the likelihood of detection.
Implement mechanisms to detect and alert users when their devices probe for sensitive SSIDs, promoting prompt action to secure the network.

**Comment by lennartkoopmann** [comment]
Done and included in the next alpha release. Thank you!

**Comment by huwilerp** [comment]
Checking in on you friend.. How are things going?
