### ISSUE TITLE
  monitoring a tagged BT-device

### ISSUE THREAD

**Issue by harry667788** [nzymedefense/nzyme#1182]
Hi

added a context to a certain Bluetooth MAC address and hoped to be able to monitor all events
of that BT-device.

(date and time of comings and goings, including duration of the presence close to the BT-tap ) 

Unfortunately I was unable to find a function to trill down all activities of the BT-device in question.

Thank's

**Comment by lennartkoopmann** [comment]
The Bluetooth subsystems remains experimental and in a very early alpha state. It does not support that yet.

**Comment by harry667788** [comment]
Do you have a timeframe for that important feature?

**Comment by lennartkoopmann** [comment]
Very unlikely to happen before v2.0.0. It's unclear if the Bluetooth functionality will remain in the product or not.

**Comment by harry667788** [comment]
>Very unlikely to happen before v2.0.0. It's unclear if the Bluetooth functionality will remain in the product or not.

BT would give Nzyme a unique advantage over other systems and we waited very long for that feature..
May I ask you what is the real reason that you are hesitating to release the BT feature?
