### ISSUE TITLE
Cannot find leader_secret

### ISSUE THREAD

**Issue by johseffer** [nzymedefense/nzyme#1195]
**Describe the bug**
I cannot find that leader secret as described in the documentation:

![image](https://github.com/user-attachments/assets/c79822fb-e200-4a35-b9ba-4cbb63443569)

But these configuration cannot be found in the tap details page, also in the authentications page.
Where i can find my leader secret?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by johseffer** [comment]
I found the values after make login again, now the secrets appear in the details page

**Comment by lennartkoopmann** [comment]
Hi! I'm re-opening this ticket because this is indeed to hard to find and very confusing.

Glad you found it!

**Comment by lennartkoopmann** [comment]
There is now a shortcut from the tap details page to the tap authentication page:

![2024-12-20_18-01](https://github.com/user-attachments/assets/bcb6fd5b-1603-4b3f-ac11-83cebbdb1a91)
