### ISSUE TITLE
Nzyme Node doesnt run on fresh install of 2.0.0-alpha.15 on Ubuntu 22.044

### ISSUE THREAD

**Issue by lozaning** [nzymedefense/nzyme#1197]
**Describe the bug**
I freshly installed 22.04 LTS of Ubuntu and then followed the steps in the documentation line by line. 
I never actually see the referenced `[main] INFO  app.nzyme.core.rest.server.NzymeHttpServer - Started web interface and REST API at [https://172.16.0.191:22900/]. Access it at: [https://172.16.0.191:22900/]` message

here is my journlctl
```
lozaning@t-pot:~$  journalctl -u nzyme -n 30
Nov 21 06:46:35 t-pot nzyme[40246]: Nov 21, 2024 6:46:35 AM liquibase.changelog
Nov 21 06:46:35 t-pot nzyme[40246]: INFO: Reading from public.databasechangelog
Nov 21 06:46:35 t-pot nzyme[40246]: Nov 21, 2024 6:46:35 AM liquibase.util
Nov 21 06:46:35 t-pot nzyme[40246]: INFO: UPDATE SUMMARY
Nov 21 06:46:35 t-pot nzyme[40246]: Nov 21, 2024 6:46:35 AM liquibase.util
Nov 21 06:46:35 t-pot nzyme[40246]: INFO: Run:                          0
Nov 21 06:46:35 t-pot nzyme[40246]: Nov 21, 2024 6:46:35 AM liquibase.util
Nov 21 06:46:35 t-pot nzyme[40246]: INFO: Previously run:             299
Nov 21 06:46:35 t-pot nzyme[40246]: Nov 21, 2024 6:46:35 AM liquibase.util
Nov 21 06:46:35 t-pot nzyme[40246]: INFO: Filtered out:                 0
Nov 21 06:46:35 t-pot nzyme[40246]: Nov 21, 2024 6:46:35 AM liquibase.util
Nov 21 06:46:35 t-pot nzyme[40246]: INFO: -------------------------------
Nov 21 06:46:35 t-pot nzyme[40246]: Nov 21, 2024 6:46:35 AM liquibase.util
Nov 21 06:46:35 t-pot nzyme[40246]: INFO: Total change sets:          299
Nov 21 06:46:35 t-pot nzyme[40246]: UPDATE SUMMARY
Nov 21 06:46:35 t-pot nzyme[40246]: Run:                          0
Nov 21 06:46:35 t-pot nzyme[40246]: Previously run:             299
Nov 21 06:46:35 t-pot nzyme[40246]: Filtered out:                 0
Nov 21 06:46:35 t-pot nzyme[40246]: -------------------------------
Nov 21 06:46:35 t-pot nzyme[40246]: Total change sets:          299
Nov 21 06:46:35 t-pot nzyme[40246]: Nov 21, 2024 6:46:35 AM liquibase.util
Nov 21 06:46:35 t-pot nzyme[40246]: INFO: Update summary generated
Nov 21 06:46:35 t-pot nzyme[40246]: Nov 21, 2024 6:46:35 AM liquibase.lockservice
Nov 21 06:46:35 t-pot nzyme[40246]: INFO: Successfully released change log lock
Nov 21 06:46:35 t-pot nzyme[40246]: Nov 21, 2024 6:46:35 AM liquibase.lockservice
Nov 21 06:46:35 t-pot nzyme[40246]: INFO: Successfully released change log lock
Nov 21 06:46:35 t-pot nzyme[40246]: Nov 21, 2024 6:46:35 AM liquibase.command
Nov 21 06:46:35 t-pot nzyme[40246]: INFO: Command execution complete
Nov 21 06:46:39 t-pot nzyme[40246]: Nov 21, 2024 6:46:39 AM org.glassfish.jersey.server.wadl.WadlFeature configure
Nov 21 06:46:39 t-pot nzyme[40246]: WARNING: JAXBContext implementation could not be found. WADL feature is disabled.
```

**To Reproduce**
1. fresh ubuntu install
2. follow directions on https://docs.nzyme.org/getting-started/installation/ubuntu-server-2204/ exactly, changing both uri to `"https://0.0.0.0:22900/"
` and changing the postgresQL password to the one set during step 2
4. check enable, then start, then check the nzyme service
4. See it's running
5. check the nzyme logs and fail to ever see successful web server initialization message
6. hit the webinterface, see self signed cert
7. only white page

**Expected behavior**
The webinterface should load I should be able to continue setting up the nzyme node install
**Screenshots**
![image](https://github.com/user-attachments/assets/b1a3218e-c70d-4892-9b7a-ea1ad6b590b6)

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04lts
 - Browser: Chrome and Firefox
 - Version 22.04LTS

**Additional context**

**Comment by lennartkoopmann** [comment]
Closing this because I believe we resolved it on Discord! The reason was a misconfigured `http_external_uri`. Pleas re-open if this issue remains.
