### ISSUE TITLE
Color settings in dashboard

### ISSUE THREAD

**Issue by JohnDoeIsKIng** [nzymedefense/nzyme#691]
Hi Lennart/everyone/community,

is it possible to change/edit the color settings of the webif with the current version (02.08.2022, 834074)? White strings and dark grey accentuations on light grey background aren't very cognizable ... at least for me.
Any hints are appreciated.
Best regards

JD.

**Comment by lennartkoopmann** [comment]
Closing this because v2.0.0 has new color schemes. Thank you!
