### ISSUE TITLE
Certain Blackvue dash cams are a bandit contact

### ISSUE THREAD

**Issue by massimo233** [nzymedefense/nzyme#778]
Certain Blackvue dash cams are detected as a esp8266_deauther. We've had four false bandit contacts with the following SSIDs: 
DR650GW-84CFDE
Blackvue650S-827198
DR650GW-808E52
DR650GW-F046E1
All of which are confirmed legitimate dash cams

**Comment by lennartkoopmann** [comment]
Closing because this will no longer be the case in v2.0.0. Thank you!
