### ISSUE TITLE
Unable to Paste 2-Factor Code During Login

### ISSUE THREAD

**Issue by kallakoras** [nzymedefense/nzyme#884]
When attempting to log in using the 2-factor authentication process, I've encountered an issue where I'm unable to paste the generated code into the designated input boxes. This problem affects both manual pasting and using password manager tools like 1Password. Additionally, typing the code too quickly results in missed digits, and the enter key does not seem to trigger any action.

Steps to Reproduce:

    Navigate to the login page.
    Enter your username and password.
    Generate a 2-factor authentication code from your authenticator app.
    Attempt to paste the code into the designated input box.

Expected Behavior:
The 2-factor authentication code should be pasteable into the input box, either manually or via password manager tools. Typing the code quickly should not result in skipped digits, and pressing the enter key should trigger the appropriate action.

Windows 10
Firefox 116.0.2

**Comment by lennartkoopmann** [comment]
Thank you! Implemented with other improvements:

* Pasting works
* Enter key submissions works
* Arrow key navigation improved, pre-selecting value automatically and positioning cursor

See: https://twitter.com/nzyme_defense/status/1723114216662426055
