### ISSUE TITLE
'<unnamed>' panicked at 'index out of bounds: the len is 2056 but the index is 3248', src/dot11/nl.rs:170:

### ISSUE THREAD

**Issue by alphafox02** [nzymedefense/nzyme#910]
**Describe the bug**
Unable to start Nzyme Tap

**To Reproduce**
Sudo systemctl start nzyme-tap.service

**Expected behavior**
Service starts, no issues using monitor mode capable interface. 

**Actual behavior**
Aug 30 14:12:28 dragon nzyme-tap[29850]: [INFO][2023-08-30 14:12:28][dot11::capture] Starting WiFi capture on [wlp48s0]
Aug 30 14:12:28 dragon nzyme-tap[29850]: [INFO][2023-08-30 14:12:28][brokers::dot11_broker] Installing WiFi broker thread <0>.
Aug 30 14:12:28 dragon nzyme-tap[29850]: thread 'main' panicked at 'index out of bounds: the len is 2056 but the index is 3248', src/dot11/nl.rs:170:[INFO][2023-08-30 14:>
Aug 30 14:12:28 dragon nzyme-tap[29850]: 28
Aug 30 14:12:28 dragon nzyme-tap[29850]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aug 30 14:12:28 dragon nzyme-tap[29850]: thread '<unnamed>' panicked at 'index out of bounds: the len is 2056 but the index is 3248', src/dot11/nl.rs:170:
Aug 30 14:12:28 dragon systemd[1]: nzyme-tap.service: Main process exited, code=exited, status=101/n/a
`

**Laptop**
 - 22.04
 - Nzyme Alpha 3

**Comment by lennartkoopmann** [comment]
Thanks! Can you post the output of `uname -a`? Does this happen on every startup of `nzyme-tap` or only sometimes?

This is the Netlink subsystem failing to parse the kernel response for a PHY. 

We may have to capture a Netlink debug to figure this out.

**Comment by alphafox02** [comment]
5.15.0.53

Happens every time as long as the WiFi config is enabled/in the conf.

**Comment by lennartkoopmann** [comment]
@uskr is working on a new and improved Netlink implementation. It is expected to come out with `alpha.4`.

Can you re-open this issue if it still doesn't work with that new release? Thank you!
