### ISSUE TITLE
Reduce effort required to list all channels in tap configuration file

### ISSUE THREAD

**Issue by lennartkoopmann** [nzymedefense/nzyme#911]
Currently, a user has to manually write down all channels they want to listen on in the tap configuration file. This can create a significant amount of time required to type all this in and should be improved.

The solution has to be built in a way where assigned channels remain the same across restarts. If they were not to stay the same, each restart of nzyme would potentially change recorded signal characteristics (because now different adapters stay on different channels for different periods of time) and throw all sorts of alerts and make analysis really confusing.

Possible idea: Optionally read from a `/etc/nzyme/tapchannels.conf` file that can be generated by a command like `nzyme-tap generate-channels > /etc/nzyme/tapchannels.conf`.

All available channels can be pulled using existing Netlink functionality in `nzyme-tap`.

**Comment by uskr** [comment]
Initial PR with this functionality is submitted.

It replicates what the current code does. That means it still does not support Wifi6e, which is on another ticket.

**Comment by lennartkoopmann** [comment]
This one can be closed, too?

**Comment by uskr** [comment]
Yes.
