### ISSUE TITLE
WiFi 6 Support

### ISSUE THREAD

**Issue by lennartkoopmann** [nzymedefense/nzyme#912]
WiFi 6 is re-using channel numbers and does not currently work with nzyme: https://en.wikipedia.org/wiki/List_of_WLAN_channels#6_GHz_(802.11ax_and_802.11be)

- [x] Find a unique WiFi6 channel notation. Channel `1` can now mean either `2.4` or `6` GHz/WiFi 6.
  - [ ] Idea: `1[6]` means channel 1 for WiFi 6
  - [ ] Alternatively, we could require to enter frequencies everywhere. Is this too much typing and too confusing?
- [x] Support WiFi 6 channels in `nzyme-tap` channel config
- [x] Support WiFi 6 channels in channel/frequency translate tables
  - [x] Node
  - [x] Tap
  - [x] Web Interface

**Comment by uskr** [comment]
With all the work on issues #920 and #911, we knocked down wifi6e support on the tap side.

**Comment by lennartkoopmann** [comment]
I think this can be closed, right?

**Comment by uskr** [comment]
I need to fix a bug on the UI side. only one I found where channel is showing as -1.

**Comment by lennartkoopmann** [comment]
OK! I'm moving it to the `alpha.5` milestone.

**Comment by uskr** [comment]
We can close this now.
