### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by shandshellin** [nzymedefense/nzyme#917]
Can v2.0 be installed over top or does it need to be a new install?

**Comment by lennartkoopmann** [comment]
Correct. The upgrade notes in the release info have the details!

**Comment by shandshellin** [comment]
where is the release info?

**Comment by lennartkoopmann** [comment]
On the downloads page: https://github.com/nzymedefense/nzyme/releases/tag/2.0.0-alpha.3
