### ISSUE TITLE
Support environment variables in tap configuration file

### ISSUE THREAD

**Issue by uskr** [nzymedefense/nzyme#926]
As posted by trevor on discord:

"I want to store as much as possible in environment variables be able to eliminate as much manual work as possible to prepare for fully automated deployments. so, be able to use the standard --> https://12factor.net/config

something like this would be especially helpful:
command line flags.
environment variables.
configuration file.

this way, I can pass variables when running containers:
podman run -it --rm \
    --name tap-02 \
    -e LEADER_SECRET=long_secret_string \
    -e LEADER_URI=https://nzyme.example.com/ \
    -e INSECURE_CERTS=true \
    -e ETH_ACTIVE=false \
    -e WIFI1=wlp1s0u1u1 \
    -e WIFI1_ACTIVE=true \
    -e WIFI2=wlp1s0u1u2 \
    -e WIFI2_ACTIVE=true \
    nzyme-tap 

or a pod or buildconfig deployment file:
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nzyme
  name: nzyme
spec:
  containers:
  - args:
    - postgres
    env:
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata
    - name: POSTGRES_USER
      value: nzyme
    - name: POSTGRES_PASSWORD
      value: nzyme
    - name: POSTGRES_DB
      value: nzyme
    image: docker.io/library/postgres:latest
    name: nzyme-postgres
    ports:
    - containerPort: 5432
      hostPort: 5432
    - containerPort: 22900
      hostPort: 22900
    tty: true
 "

**Comment by uskr** [comment]
Really good use case is deploy taps through podman or other container tech to allow for fast self healing or mass update through a central registry.

**Comment by trevorbryant** [comment]
I wanted to follow up to see if there is a planned activity for this.

In the last few release updates, I didn't find in the code that expands environment variables before passing them to TOML. So, the environment variable expansions that you put in a config are just being parsed as literal strings and not expanded unless something somewhere else is doing it and I missed it (which I don't know is the case as my builds still fail without literal hardcoded strings). 

To ease the packaging and deployment of nodes and taps, something that I'm looking for is that the application(s) would load a configuration file, then overwrite the config fields with values from known environment variables and/or CLI parameters after loading the configuration file. A hierarchy, highest to lowest priority, that would look similar to this:

1. Command line flags
2. Environment variables
3. Configuration file

That way, we could run something like this: 
```
podman run ... \
-e node_name=node-01 \
-e data_directory=/opt/nzyme \
-e ntp_server=time.nist.gov \
-e crypto_dir=/opt/nzyme/crypto \
-e rest_listen_uri="https://0.0.0.0:22900/" \
-e http_external_uri="https://nzyme.example.com/"
...
```

We could set a testing value (or not set a value) for secrets in the config file (i.e. it's not specific to any environment), and then have the service set the environment variables to override those secrets in production, and when the application loads it would:

1. Load the configuration file.
2. Overwrite fields with values from environment variables.
3. Overwrite fields with values from command line.

This way, the most specific way to specify an option always takes precedence, and there's no weird variable expansion in configuration files.

Again, apologies if I missed something in the recent releases if this was implemented.

**Comment by lennartkoopmann** [comment]
Moved this into the proper milestone. @trevorbryant, when we talked about this a few days ago, I was wrong: The `nzyme-tap` configuration file does not currently support environment variables, but we will build that. Currently, only `nzyme-node` supports environment variables.

**Comment by lennartkoopmann** [comment]
Done and documented here: https://docs.nzyme.org/configuration/misc/environment-variables/

Thanks everyone!
