### ISSUE TITLE
Web IF not reachable

### ISSUE THREAD

**Issue by JohnDoeIsKIng** [nzymedefense/nzyme#932]
Dear community,
hey Lennart,

I've built a dpkg-package from a fresh git clone without issues (Build log as attachment).
But when I try to install this over my running nzyme (1.3), the webif is unavailable.
During installation I've been asked whether to keep my nzyme.conf or not. I kept it (N).
For me that means that the web if should still reside at 192.*.*.*:22900 as I've configured in my nzyme.conf - but it doesn't.
Any hints how to circumvent that ?
Best regards

JD.
[NzymeBuild.log](https://github.com/nzymedefense/nzyme/files/12607590/NzymeBuild.log)

**Comment by lennartkoopmann** [comment]
Please post the nzyme log file and confirm that the nzyme service is running. Did you replace your configuration file with the v2.0 file? The format changed.

**Comment by JohnDoeIsKIng** [comment]
Dear community,
dear Lennart,

thanx for the hint and please apologize for the delay.
I've diffed the old and the new nzyme.conf.
Am I right that with the new one

- the python{} struct
- the alerting{} struct
- the ulinks[]-array and the whole 
- 802_11_ parts are gone ?

Where am I to put them from my old nzyme.conf in the actual version ?
Best regards

JD.

**Comment by lennartkoopmann** [comment]
Hi,

please use the new example config file. The old config file has changed so much, it makes no sense to try to modify it to work with v2.0.
