### ISSUE TITLE
Properly handle SSID's with utf-8 null bytes and other non-ascii like emojis

### ISSUE THREAD

**Issue by uskr** [nzymedefense/nzyme#935]
- [ ] Make sure all non-ascii utf-8 characters that should be supported on SSID's are supported
   - [ ] tap
   - [ ] node
   - [ ] web
   
- [ ] Make sure emojis are supported
    - [ ] tap
    - [ ] node
    - [ ] web

- [ ] Handle corner cases like malformed SSID's that have only a null byte
    - [ ] tap
    - [ ] node
    - [ ] web

**Comment by lennartkoopmann** [comment]
Let's always set the milestone to the estimated release this will go out with. For example, this will likely be `alpha.5`. This way, we can filter all `alpha.x` issues before release and build the changelog. Alternatively, this also works with `git diff` but usually the changelog is built on higher-level information like issues, not individual commits.

**Comment by uskr** [comment]
Done! Thanks.

**Comment by lennartkoopmann** [comment]
This was solved in #988 by sanitizing SSIDs and stripping them of invisible characters during ingestion. It handles invisible unicode characters, repetitive whitespaces, tabs, null bytes etc.

The similar SSID and/or restricted SSID substring alerts will catch this.
