### ISSUE TITLE
Nzyme-tap Active: activating

### ISSUE THREAD

**Issue by dgr1003** [nzymedefense/nzyme#946]
I have an ALFA AWUS036NHR and a raspberry 4B 4Gbs

After following all the steps, in the GUI the tap shows always ofline.

Y execute the status to see what happens, and I get:

Active: activating (auto-restart) (Result: exit-code) since...

Later in loglevel info i got 
Code=exited
status=78

What might be the problem? Is maybe some misconfiguration i made?

**Comment by uskr** [comment]
Hi,

Do you think you can manually start the tap with the --debug-level DEBUG parameter and attach here a full log since start, until it exits?

I don't believe we can help much with the limited information you provided.

Thank you!

**Comment by dgr1003** [comment]
I tried to start the tap with --debug-level but I get an error about unrecognized option. So i  tried with journalctl -xe and this is what I get :


journalctl -xe
░░ A stop job for unit nzyme-tap.service has finished.
░░
░░ The job identifier is 12736 and the job result is done.
oct 23 08:40:34 raspberrypi systemd[1]: Started Nzyme-Tap.
░░ Subject: A start job for unit nzyme-tap.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit nzyme-tap.service has finished successfully.
░░
░░ The job identifier is 12736.
oct 23 08:40:34 raspberrypi sudo[11866]: pam_unix(sudo:session): session closed for user root
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][logging] Initialized logging with level filter [INFO].
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][nzyme_tap] Starting nzyme tap version [2.0.0-alpha.4].
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][nzyme_tap] Parsed and loaded configuration.
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][ethernet::capture] Available network device: wlan0 (no description): [192.168.0.189, fe80::40f1:b3b7:428f:6795]
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][ethernet::capture] Available network device: any (Pseudo-device that captures on all interfaces): [no interface addresses]
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][ethernet::capture] Available network device: lo (no description): [127.0.0.1, ::1]
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][ethernet::capture] Available network device: eth0 (no description): [no interface addresses]
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][ethernet::capture] Available network device: wlan1 (no description): [no interface addresses]
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][ethernet::capture] Available network device: bluetooth0 (Bluetooth adapter number 0): [no interface addresses]
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][ethernet::capture] Available network device: bluetooth-monitor (Bluetooth Linux Monitor): [no interface addresses]
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][ethernet::capture] Available network device: nflog (Linux netfilter log (NFLOG) interface): [no interface addresses]
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][ethernet::capture] Available network device: nfqueue (Linux netfilter queue (NFQUEUE) interface): [no interface addresses]
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][ethernet::capture] Available network device: dbus-system (D-Bus system bus): [no interface addresses]
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][ethernet::capture] Available network device: dbus-session (D-Bus session bus): [no interface addresses]
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][nzyme_tap] Skipping disabled Ethernet interface [enp6s0].
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][brokers::dot11_broker] Installing WiFi broker thread <0>.
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][dot11::capture] Starting WiFi capture on [wlan1]
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][brokers::ethernet_broker] Installing ethernet broker thread <0>.
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][dot11::capture] Temporarily disabling interface [wlan1] ...
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][dot11::channel_hopper] Available adapters and channels: {"wlan1": [2412, 2417, 2422, 2427, 2432, 2437, 2442, 2447, 2452, 245>
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][dot11::capture] Device [wlan1] is now down.
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][dot11::capture] Enabling monitor mode on interface [wlan1] ...
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [ERROR][2023-10-23 08:40:34][nzyme_tap] Could not initialize ChannelHopper: WiFi adapter [wlan1] does not support channel <36 / 5180 MHz>.
oct 23 08:40:34 raspberrypi nzyme-tap[11911]: [INFO][2023-10-23 08:40:34][dot11::capture] Device [wlan1] is now in monitor mode.
oct 23 08:40:34 raspberrypi systemd[1]: nzyme-tap.service: Main process exited, code=exited, status=71/OSERR
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ An ExecStart= process belonging to unit nzyme-tap.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 71.
oct 23 08:40:34 raspberrypi systemd[1]: nzyme-tap.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit nzyme-tap.service has entered the 'failed' state with result 'exit-code'.


What I got in sudo systemctl status nzyme-tap is: 

● nzyme-tap.service - Nzyme-Tap
     Loaded: loaded (/lib/systemd/system/nzyme-tap.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2023-10-23 09:00:54 CEST; 4s ago
       Docs: https://github.com/lennartkoopmann/nzyme
    Process: 19930 ExecStart=/usr/bin/nzyme-tap --configuration-file /etc/nzyme/nzyme-tap.conf --log-level info (code=exited, status=71)
   Main PID: 19930 (code=exited, status=71)
        CPU: 30ms

**Comment by uskr** [comment]
Apologies for the confusion. I meant --log-level debug.

But the logs already points us to a clue.

Could you also post your tap config file?

Thank you!
